# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [20]:
!git clone https://github.com/rougier/numpy-100.git

Cloning into 'numpy-100'...
remote: Enumerating objects: 1124, done.
remote: Counting objects: 100% (512/512), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 1124 (delta 458), reused 392 (delta 392), pack-reused 612 (from 3)
Receiving objects: 100% (1124/1124), 540.77 KiB | 15.90 MiB/s, done.
Resolving deltas: 100% (656/656), done.


In [22]:
!wget https://raw.githubusercontent.com/rougier/numpy-100/master/generators.py

--2026-06-08 20:48:44--  https://raw.githubusercontent.com/rougier/numpy-100/master/generators.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4421 (4.3K) [text/plain]
Saving to: ‘generators.py.1’

generators.py.1     100%[===================>]   4.32K  --.-KB/s    in 0.001s  

2026-06-08 20:48:45 (8.04 MB/s) - ‘generators.py.1’ saved [4421/4421]



In [23]:
pip install mdutils

In [27]:
%cd numpy-100

/content/numpy-100


In [28]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [29]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [34]:
print (np.__version__)

2.0.2


#### 3. Create a null vector of size 10 (★☆☆)

In [35]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [36]:
print(np.zeros(10).nbytes)

80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [41]:

help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [43]:
vector = np.zeros(10)
vector[4] = 1
print (vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [44]:
vector = np.arange (10,50)
print (vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [49]:
import numpy as np
v = np.arange(1,5)
v_reversed = v[::-1]
print(v_reversed)

[4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [50]:
v = np.arange(0,9)
v = v.reshape(3,3)
print (v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [52]:
import numpy as np

arr = np.array([1,2,0,0,4,0])
indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [53]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [54]:
v = np.random.random ((3,3,3))
print (v)

[[[0.11006954 0.70182255 0.37521802]
  [0.11239187 0.22974866 0.9392769 ]
  [0.73810746 0.24530828 0.81683024]]

 [[0.45184641 0.83200861 0.86438799]
  [0.22917399 0.11787763 0.70787813]
  [0.20843462 0.69177726 0.97532423]]

 [[0.00871921 0.0934212  0.61958417]
  [0.53967651 0.06367364 0.26540955]
  [0.81016146 0.96465991 0.57635906]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [56]:
 v = np.random.random((10,10))
 print(v.min())
 print(v.max())

0.004204097622340086
0.9965458489406822


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [57]:
v = np.random.random(30)
print(v.mean())

0.546791321965544


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [59]:
v = np.ones((5,5))
v[1:-1,1:-1] = 0
print(v)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [62]:
v = np.ones((5,5))
v_border = np.pad(v, pad_width=1, constant_values=0)
print(v_border)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan, false, false, nan, true, false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [65]:
v = np.diag(np.arange(1,5)).astype(int)
print (v)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [68]:
Z = np.zeros((8,8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [69]:
import numpy as np
shape = (6,7,8)
index = 100 - 1
x,y,z = np.unravel_index(index,shape)

print(x,y,z)

1 5 3


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [71]:
import numpy as np
checkerboard = np.tile([[0,1], [1,0]], (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [75]:


X = np.random.random((5,5))
X_norm = (X - X.mean()) / X.std()

print("Original", X)
print("Normalized", X_norm)

Original [[0.65836805 0.02813726 0.07154883 0.74450102 0.68053801]
 [0.09291897 0.43870459 0.60439015 0.38808998 0.8180242 ]
 [0.09931443 0.55983208 0.71707311 0.68540607 0.75410164]
 [0.05464391 0.7097471  0.81531624 0.58742336 0.78313636]
 [0.59018052 0.51243604 0.45651486 0.20139485 0.2669756 ]]
Normalized [[ 0.63329786 -1.77658828 -1.61059043  0.96265439  0.71807168]
 [-1.52887498 -0.20665463  0.42689634 -0.40019558  1.24379346]
 [-1.50441993  0.25651448  0.85777515  0.73668625  0.99936538]
 [-1.67523172  0.82976182  1.23343872  0.36201845  1.11038879]
 [ 0.37256132  0.07528078 -0.13855148 -1.11408326 -0.86331459]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [76]:
import numpy as np

color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
colors = np.array([(255,0,0,255),(0,255,0,255),(0,0,255,255)], dtype=color_dtype)
print(colors)
print(colors['r'])

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]
[255   0   0]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [77]:
 A = np.random.random((5,3))
 B = np.random.random ((3,2))

 C = np.dot(A,B)

 print(C)

[[0.64666655 1.09880297]
 [0.67075868 1.08421613]
 [0.72813948 0.97149506]
 [0.74827529 0.81744061]
 [0.971526   1.39414496]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [78]:
A = np.arange(11)
A[(A > 3) & (A < 8)] *= -1
print(A)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [80]:
9, 10

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [82]:
warning
warning
warning

NameError: name 'warning' is not defined

#### 29. How to round away from zero a float array ? (★☆☆)

In [84]:
import numpy as np

def round_away_from_zero(x):
  return np.where(x>0, np.ceil(x), np.floor(x))

X = np.array([1.2,1.8, -1.2, -1.8, 0.0])
print(round_away_from_zero(X))

[ 2.  2. -2. -2.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [85]:
A = np.array([1,2,3,4])
B = np.array ([2,4,6,8])

common = np.intersect1d(A,B)
print(common)

[2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [87]:
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [88]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [90]:
from datetime import datetime, timedelta

today = datetime.today()
yesterday = datetime.today() - timedelta(days=1)
tomorrow = datetime.today() + timedelta(days=1)

print("yesterday", yesterday)
print("today", today)
print("tomorrow", tomorrow)

yesterday 2026-06-08 01:16:55.366663
today 2026-06-09 01:16:55.366580
tomorrow 2026-06-10 01:16:55.366888


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [91]:
import pandas as pd
dates = pd.date_range(start='2016-07-01', end='2016-07-31')
print(dates)

DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [94]:
A = np.ones(3)
B = np.ones(3)*2
np.add(A,B, out=B)
np.divide(A,2, out=A)
np.negative(A, out=A)
np.multiply(A,B, out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [107]:
X = np.random.uniform(0,10,5) #5 numbers between 0 to 10
print(X)
print(np.floor(X))
print(X.astype(int))
print(np.trunc(X))
print(np.modf(X)[1])



[0.19999579 5.14281772 0.93315095 8.48134932 4.75576232]
[0. 5. 0. 8. 4.]
[0 5 0 8 4]
[0. 5. 0. 8. 4.]
[0. 5. 0. 8. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [116]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [120]:
def generate():
  for i in range(10):
    yield(i)

arr = np.fromiter(generate(),dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [126]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [130]:
x = np.random.random(10)
np.sort(x)

array([0.19716685, 0.2087544 , 0.28417602, 0.35658981, 0.49653577,
       0.56719692, 0.62855861, 0.63102178, 0.63499742, 0.94327381])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [131]:
Z = np.arange(10)
print(sum(Z))

45


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [134]:
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)

print(A,B)
equal = np.array_equal(A,B)
print(equal)

[2 3 7 1 9] [6 4 3 8 0]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [138]:
Z = np.arange(5)
print(Z)
Z.flags.writeable = False

[0 1 2 3 4]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [160]:
z = np.random.rand(10,2)

x = z[:, 0]
y = z[:, 1]

r = np.hypot(x,y)
theta = np.arctan2(y,x)

polar = np.column_stack((r,theta))

print(polar)


[[0.61390137 0.42665559]
 [0.14129895 0.82869929]
 [0.44551642 0.82768108]
 [0.70821779 0.41967565]
 [0.99461619 0.34011755]
 [0.9559361  0.70089569]
 [0.96128183 0.17305996]
 [1.093063   0.49122628]
 [0.78003259 1.28867212]
 [0.35937773 0.50720167]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [162]:
 z = np.random.rand(10)
 print(z)
 z[z.argmax()] = 0
 print (z)

[0.00349757 0.17240338 0.46520193 0.44484989 0.21260312 0.26224802
 0.73617989 0.64056946 0.85156226 0.1903858 ]
[0.00349757 0.17240338 0.46520193 0.44484989 0.21260312 0.26224802
 0.73617989 0.64056946 0.         0.1903858 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [180]:
n = 10

Z = np.zeros((n,n),dtype = [('x',np.float64), ('y', np.float64)])

x = np.linspace(0,1,n)
y = np.linspace(0,1,n)

x,y = np.meshgrid(x,y)

Z['x'] = x
Z['y'] = y



[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [186]:
X = np.array([1,2,3])
Y = np.array([4,5,6])

C= 1.0/ (X[:, None] - Y)
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [191]:
for dtype in [np.int8, np.int32, np.int64, np.uint8, np.uint32, np.uint64, np.float32, np.float64]:

  if np.issubdtype(dtype, np.integer):
    info = np.iinfo(dtype)
  else:
    info = np.finfo(dtype)

  print(dtype.__name__, info.min, info.max)



int8 -128 127
int32 -2147483648 2147483647
int64 -9223372036854775808 9223372036854775807
uint8 0 255
uint32 0 4294967295
uint64 0 18446744073709551615
float32 -3.4028235e+38 3.4028235e+38
float64 -1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [193]:
np.set_printoptions(threshold=np.inf)

a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [198]:
Z = np.array([10,20,30])
value = 33

closest = Z[np.abs(Z-value).argmin()]
print(closest)

2
30


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [8]:
import numpy as np
dtype = [('position', [('x', np.float32), ('y', np.float32)]), ('color', [('r',np.uint8), ('g', np.uint8), ('b', np.uint8)])]
Z = np.zeros(10, dtype=dtype)
print(Z)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [14]:
Z = np.random.rand(100,2)

distance = np.sqrt(((Z[1:]- Z[:-1])**2).sum(axis=1))
print(distance)

[0.5832753  0.79761574 0.77526167 0.66016525 0.12357103 0.12514858
 0.35337049 0.24543752 0.27714113 0.66167555 0.50278959 0.19661535
 0.3602193  0.51247271 0.54565728 0.43449788 0.43975665 0.63138862
 0.42884957 0.31839297 0.39227501 0.33706477 0.17655242 0.75091649
 0.4240767  1.06213093 0.77809107 0.97065067 0.65966918 0.15169155
 0.77058797 0.82469719 0.44320302 0.09353425 0.3616188  0.23424885
 0.40772711 0.55521588 0.44461117 0.56764053 0.96447674 0.36723327
 0.73265506 0.3653872  0.1920991  0.87020035 0.07784759 0.33244275
 0.42600515 0.48033309 0.29308265 0.45490265 0.34664522 0.67522859
 0.98453009 0.64393759 0.49154817 0.05987749 0.24057875 0.24919955
 0.10963587 0.18148483 0.36013413 0.7803841  0.37867586 0.12272111
 0.32041606 0.46006111 0.2577918  0.90498231 0.86024671 0.12837374
 0.38443498 0.24379058 0.60008686 0.19127499 0.43460181 1.02890255
 0.42847261 0.26197748 0.21530716 0.2427706  0.53669459 0.47736838
 0.35301098 0.34846539 0.49806411 0.19889271 0.46550925 0.6677

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [22]:
Z = np.arange(10, dtype=np.float32)

Z = Z.astype(np.int32)

print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [21]:
data = np.genfromtxt("file.txt", delimiter=",")
print(data)

FileNotFoundError: file.txt not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [27]:
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
  print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [33]:
n = 10
x = np.linspace(-1,1,n)
y = np.linspace(-1,1,n)

X,Y = np.meshgrid(x,y)

sigma = 0.2
G = np.exp(-(X**2+Y**2)/(2*sigma**2))
print(G)

[[1.38879439e-11 1.93776925e-09 7.86683682e-08 9.29249200e-07
  3.19373018e-06 3.19373018e-06 9.29249200e-07 7.86683682e-08
  1.93776925e-09 1.38879439e-11]
 [1.93776925e-09 2.70374774e-07 1.09765093e-05 1.29657100e-04
  4.45617596e-04 4.45617596e-04 1.29657100e-04 1.09765093e-05
  2.70374774e-07 1.93776925e-09]
 [7.86683682e-08 1.09765093e-05 4.45617596e-04 5.26373946e-03
  1.80909100e-02 1.80909100e-02 5.26373946e-03 4.45617596e-04
  1.09765093e-05 7.86683682e-08]
 [9.29249200e-07 1.29657100e-04 5.26373946e-03 6.21765240e-02
  2.13694068e-01 2.13694068e-01 6.21765240e-02 5.26373946e-03
  1.29657100e-04 9.29249200e-07]
 [3.19373018e-06 4.45617596e-04 1.80909100e-02 2.13694068e-01
  7.34443672e-01 7.34443672e-01 2.13694068e-01 1.80909100e-02
  4.45617596e-04 3.19373018e-06]
 [3.19373018e-06 4.45617596e-04 1.80909100e-02 2.13694068e-01
  7.34443672e-01 7.34443672e-01 2.13694068e-01 1.80909100e-02
  4.45617596e-04 3.19373018e-06]
 [9.29249200e-07 1.29657100e-04 5.26373946e-03 6.21765240e

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [37]:
n = 10
p = 20

Z = np.zeros((n,n))

indices = np.random.choice(range(n*n),p, replace=False)
print(indices)
Z.flat[indices] = 1
print(Z)


[51 55 23 35 30 18 73  8 77  4 60 88 32 58 83  0 17 61 62  2]
[[1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [43]:
X = np.random.rand(2,2)
print(X)
print(X - X.mean(axis=1))

[[0.65639668 0.81174699]
 [0.43499057 0.44583874]]
[0.73407184 0.44041466]
[[-0.07767516  0.37133234]
 [-0.29908126  0.00542408]]


#### 59. How to sort an array by the nth column? (★★☆)

In [57]:
X = [[1,2,3],
     [5,13,9],
     [10,11,12]]
n = 1 #sort by column 1

sorted_data = sorted(X, key=lambda x:x[n])
print(sorted_data)

[[1, 2, 3], [10, 11, 12], [5, 13, 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [62]:
A = np.zeros(4).reshape(2,2)
print(A)
null_cols = np.any(A==0 )
print(null_cols)

[[0. 0.]
 [0. 0.]]
True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [71]:
x = 10
arr = np.arange(10)
nearest = arr[np.abs(arr - x).argmin()]


[0 1 2 3 4 5 6 7 8 9]
[10  9  8  7  6  5  4  3  2  1]
9


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [99]:
a = np.array([[1, 2, 3]])   # shape (1,3)
b = np.array([[10], [20], [30]])  # shape (3,1)

result = np.empty((3, 3), dtype=int)

for (i, j), val in np.ndenumerate(np.zeros((3, 3))):
    result[i, j] = a[0, j] + b[i, 0]

print(result)



[[11 12 13]
 [21 22 23]
 [31 32 33]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class = NamedArray(np.ndarray)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)